// Persisted Values
#define DEFAULT_WEATHER_SCALE "F"  // F Fahrenheit or C Celsius
#define DEFAULT_DEBUG_MODE false
#define DEFAULT_WEATHER_SERVICE "yahoo"
#define DEFAULT_FACE_COLOR "duke"
#define DEFAULT_DISPLAY_BATTERY true
#define DEFAULT_ALERT_BLUETOOTH true
#define DEFAULT_VIBE_TIME_SIGNAL false
// #define DEFAULT_VIBE_START_TIME true
// #define DEFAULT_VIBE_END_TIME true
#define DEFAULT_VIBE_START_TIME 7
#define DEFAULT_VIBE_END_TIME 22

#define KEY_DEBUG_MODE 0
#define KEY_WEATHER_SERVICE 1
#define KEY_FACE_COLOR 4
#define KEY_WEATHER_SCALE 2
#define KEY_DISPLAY_BATTERY 3
#define KEY_ALERT_BLUETOOTH 5
#define KEY_VIBE_TIME_SIGNAL 6
#define KEY_VIBE_START_TIME 7
#define KEY_VIBE_END_TIME 8

